name: Feature
on:
  push:
    branches:
      - feature/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Buildbox Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          file: buildbox.dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/buildbox:${{ env.GITHUB_REF_SLUG }}
      - name: E2E Runner Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          file: e2e.dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/e2e-runner:${{ env.GITHUB_REF_SLUG }}
      - name: List Docker images
        shell: bash
        run: |
          docker images 

